Add Module11 level 06 - 08
dzmitri-litvinov/AutoPark pull request #6
Opened 2021-05-03 12:10 UTC by dzmitri-litvinov

2021-05-03 18:01 UTC, PushMeNow requested changes
Hi man!
I did some comment. Let me know if any question.

2021-05-03 18:01 UTC, PushMeNow commented on autopark/Program.cs
> +            Console.WriteLine(new string('*', scrWidth) + '\n');
I see you use same line some times. Move this action in separate method. Keep DRY approach.

2021-05-03 18:01 UTC, PushMeNow commented on autopark/Program.cs
> +                              "////////////");
Again move it in separate method

2021-05-03 18:01 UTC, PushMeNow commented on autopark/SupportClasses/SparePartsDictionary.cs
> +            SparePartsNames = LoadSpareParts(inFile).ToArray();
I don't the reason to keep parts in global variable. Transmit result of method LoadSpareParts in CreateDictionary

2021-05-03 18:01 UTC, PushMeNow commented on autopark/SupportClasses/SparePartsDictionary.cs
> +        public IEnumerable<string> LoadSpareParts(string inFile)
Remember about incapsulation. User mustn't know about this method.

2021-05-03 18:01 UTC, PushMeNow commented on autopark/SupportClasses/SparePartsDictionary.cs
> +        public void CreateDictionary()
Again incapsulation

2021-05-04 14:49 UTC, dzmitri-litvinov commented on autopark/Program.cs
> +            Console.WriteLine(new string('*', scrWidth) + '\n');
![image](https://user-images.githubusercontent.com/79978383/117022542-ffe90a80-ad00-11eb-80d6-d62c18548d3c.png)
Done

2021-05-04 14:55 UTC, dzmitri-litvinov commented on autopark/Program.cs
> +                              "////////////");
![image](https://user-images.githubusercontent.com/79978383/117023494-d5e41800-ad01-11eb-9cb3-6504facd5915.png)
![image](https://user-images.githubusercontent.com/79978383/117023529-dc728f80-ad01-11eb-8f96-95c588cb981f.png)
Done

2021-05-04 14:56 UTC, dzmitri-litvinov commented on autopark/Program.cs
> +                              "////////////");
I wrote such code to visually separate levels in Main

2021-05-04 15:12 UTC, dzmitri-litvinov commented on autopark/SupportClasses/SparePartsDictionary.cs
> +        public IEnumerable<string> LoadSpareParts(string inFile)
![image](https://user-images.githubusercontent.com/79978383/117026160-383e1800-ad04-11eb-9fd7-52aca3f18a87.png)
Done

2021-05-04 15:13 UTC, dzmitri-litvinov commented on autopark/SupportClasses/SparePartsDictionary.cs
> +        public void CreateDictionary()
![image](https://user-images.githubusercontent.com/79978383/117026336-5e63b800-ad04-11eb-8f30-3633ceee98ea.png)
Done

2021-05-04 15:22 UTC, dzmitri-litvinov commented on autopark/SupportClasses/SparePartsDictionary.cs
> +            SparePartsNames = LoadSpareParts(inFile).ToArray();
![image](https://user-images.githubusercontent.com/79978383/117027323-43457800-ad05-11eb-9dcb-12762098fb55.png)
Shall I overload the method CreateDictionary in such a way, so it has an `IEnumerable<string> parts` argument?

2021-05-05 18:02 UTC, PushMeNow approved these changes
Approved

2021-05-05 18:06 UTC, merged